### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by jkenlooper** [ZWhiteShadow/Personal_Website#1]
https://github.com/ZWhiteShadow/Personal_Website/blob/104fc4541d2e45b051aaf751fa956ae681351649/index.html#L48

Just thought I'd say hi.  :)

**Comment by ZWhiteShadow** [comment]
as·pir·ing
/əˈspī(ə)riNG/
 Learn to pronounce
adjective
directing one's hopes or ambitions toward becoming a specified type of person.
"an aspiring artist"

:) Looks good to me. Hi back

**Comment by jkenlooper** [comment]
Oh, I guess it is misspelled on your GitHub profile, then.
